image:
  repository: fedlify/cicd-example
  tag: 2139fc9
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: nginx
  host: app.fedlify.com
  path: /
  tls: true