apiVersion: v1
kind: Service
metadata:
  name: {{ include "cicd-example.fullname" . }}
  namespace:  {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
  selector:
    app: {{ include "cicd-example.name" . }}
